# Generated by Django 3.1 on 2020-09-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blogname', models.CharField(max_length=100)),
                ('blogtitle', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
