# Generated by Django 3.1 on 2020-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('quary1', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
