# Generated by Django 3.1 on 2020-09-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloghome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usrname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('pass1', models.IntegerField()),
            ],
        ),
    ]
