# Generated by Django 3.1 on 2020-09-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloghome', '0002_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='pass1',
            field=models.CharField(max_length=100),
        ),
    ]
